title: One-Shot Facial Recognition Challenge

short_description: Develop a model that can recognize faces with only one example per person.

description: templates/description.html

evaluation_details: templates/evaluation_details.html

terms_and_conditions: templates/terms_and_conditions.html

image: images/logo.png

submission_guidelines: templates/submission_guidelines.html

evaluation_script: evaluation_script.zip

remote_evaluation: True

is_docker_based: True

is_static_dataset_code_upload: True

start_date: 2025-03-15 00:00:00

end_date: 2025-05-15 23:59:59

published: False

allowed_email_domains: []  # Empty list means all email domains are allowed

blocked_emails_domains: []  # No blocked domains

leaderboard:
  - id: 1
    schema:
      {
        "labels": ["Accuracy", "F1 Score", "Processing Time (s)", "Total"],
        "default_order_by": "Total",
        "metadata": {
          "Accuracy": {
            "sort_ascending": False,
            "description": "Classification accuracy across all test images",
          },
          "F1 Score": {
            "sort_ascending": False,
            "description": "F1 score (harmonic mean of precision and recall)",
          },
          "Processing Time (s)": {
            "sort_ascending": True,
            "description": "Average processing time per image in seconds",
          },
          "Total": {
            "sort_ascending": False,
            "description": "Weighted sum of metrics (0.5*Accuracy + 0.3*F1 + 0.2*Time)",
          }
        }
      }

challenge_phases:
  - id: 1
    name: Development Phase
    description: templates/challenge_phase_1_description.html
    leaderboard_public: True
    is_public: True
    is_submission_public: False
    start_date: 2025-03-15 00:00:00
    end_date: 2025-04-15 23:59:59
    test_annotation_file: annotations/test_annotations_devsplit.json
    codename: dev_phase
    max_submissions_per_day: 5
    max_submissions: 50
    default_submission_meta_attributes:
      - name: method_name
        is_visible: True
      - name: method_description
        is_visible: True
      - name: project_url
        is_visible: True
      - name: publication_url
        is_visible: True
    submission_meta_attributes:
      - name: ModelArchitecture
        description: Type of model architecture used
        type: radio
        options: ["CNN", "Vision Transformer", "ResNet", "Siamese Network", "Other"]
        required: True
      - name: PretrainedModel
        description: Was a pre-trained model used?
        type: boolean
        required: True
      - name: DataAugmentation
        description: Data augmentation techniques used
        type: checkbox
        options: ["Rotation", "Flipping", "Color Jitter", "None"]
      - name: AdditionalTrainingData
        description: Any additional training data used?
        type: boolean
        required: True
    is_restricted_to_select_one_submission: False
    allowed_submission_file_types: ".py, .zip, .tar.gz"

  - id: 2
    name: Testing Phase
    description: templates/challenge_phase_2_description.html
    leaderboard_public: True
    is_public: True
    is_submission_public: False
    start_date: 2025-04-16 00:00:00
    end_date: 2025-05-15 23:59:59
    test_annotation_file: annotations/test_annotations_testsplit.json
    codename: test_phase
    max_submissions_per_day: 2
    max_submissions: 10
    default_submission_meta_attributes:
      - name: method_name
        is_visible: True
      - name: method_description
        is_visible: True
      - name: project_url
        is_visible: True
      - name: publication_url
        is_visible: True
    submission_meta_attributes:
      - name: ModelArchitecture
        description: Type of model architecture used
        type: radio
        options: ["CNN", "Vision Transformer", "ResNet", "Siamese Network", "Other"]
        required: True
      - name: PretrainedModel
        description: Was a pre-trained model used?
        type: boolean
        required: True
      - name: DataAugmentation
        description: Data augmentation techniques used
        type: checkbox
        options: ["Rotation", "Flipping", "Color Jitter", "None"]
      - name: AdditionalTrainingData
        description: Any additional training data used?
        type: boolean
        required: True
    is_restricted_to_select_one_submission: True
    allowed_submission_file_types: ".py, .zip, .tar.gz"

dataset_splits:
  - id: 1
    name: Development Split
    codename: dev_split
  - id: 2
    name: Test Split
    codename: test_split

challenge_phase_splits:
  - challenge_phase_id: 1
    leaderboard_id: 1
    dataset_split_id: 1
    visibility: 3
    leaderboard_decimal_precision: 4
    is_leaderboard_order_descending: True
  - challenge_phase_id: 2
    leaderboard_id: 1
    dataset_split_id: 2
    visibility: 3
    leaderboard_decimal_precision: 4
    is_leaderboard_order_descending: True