title: Confidential Test Data Challenge
short_description: A challenge with hidden test data to prevent manual labeling.
description: templates/description.html
evaluation_details: templates/evaluation_details.html
terms_and_conditions: templates/terms_and_conditions.html
image: images/logo.jpg
submission_guidelines: templates/submission_guidelines.html
evaluation_script: evaluation_script.zip
remote_evaluation: False
is_docker_based: False
start_date: 2025-03-01 00:00:00
end_date: 2025-12-31 23:59:59
published: True

leaderboard:
  - id: 1
    schema:
      {
        "labels": ["Accuracy", "Precision", "Recall", "F1-Score"],
        "default_order_by": "F1-Score",
        "metadata": {
          "Accuracy": {
            "sort_ascending": False,
            "description": "Proportion of correct predictions.",
          },
          "Precision": {
            "sort_ascending": False,
            "description": "Proportion of true positive predictions.",
          },
          "Recall": {
            "sort_ascending": False,
            "description": "Proportion of actual positives correctly identified.",
          },
          "F1-Score": {
            "sort_ascending": False,
            "description": "Harmonic mean of Precision and Recall.",
          }
        }
      }

challenge_phases:
  - id: 1
    name: Development Phase
    description: templates/challenge_phase_1_description.html
    leaderboard_public: False
    is_public: True
    is_submission_public: False
    start_date: 2025-03-01 00:00:00
    end_date: 2025-06-30 23:59:59
    test_annotation_file: annotations/test_annotations_dev.json
    codename: dev_phase
    max_submissions_per_day: 5
    max_submissions_per_month: 50
    max_submissions: 100
    default_submission_meta_attributes:
      - name: method_name
        is_visible: True
      - name: method_description
        is_visible: True
      - name: project_url
        is_visible: False
      - name: publication_url
        is_visible: False
    submission_meta_attributes:
      - name: ModelArchitecture
        description: Describe your model architecture.
        type: text
        required: True
      - name: TrainingData
        description: Specify the data used for training.
        type: text
        required: True
      - name: ExternalData
        description: Did you use any external data? If yes, provide details.
        type: boolean
        required: True
    is_restricted_to_select_one_submission: True
    is_partial_submission_evaluation_enabled: False
    allowed_submission_file_types: ".zip, .tar.gz"

  - id: 2
    name: Testing Phase
    description: templates/challenge_phase_2_description.html
    leaderboard_public: True
    is_public: True
    is_submission_public: False
    start_date: 2025-07-01 00:00:00
    end_date: 2025-12-31 23:59:59
    test_annotation_file: annotations/test_annotations_test.json
    codename: test_phase
    max_submissions_per_day: 2
    max_submissions_per_month: 20
    max_submissions: 50
    default_submission_meta_attributes:
      - name: method_name
        is_visible: True
      - name: method_description
        is_visible: True
      - name: project_url
        is_visible: False
      - name: publication_url
        is_visible: False
    submission_meta_attributes:
      - name: ModelVersion
        description: Version of the model submitted.
        type: text
        required: True
      - name: TrainingData
        description: Specify the data used for training.
        type: text
        required: True
      - name: ExternalData
        description: Did you use any external data? If yes, provide details.
        type: boolean
        required: True
    is_restricted_to_select_one_submission: True
    is_partial_submission_evaluation_enabled: False
    allowed_submission_file_types: ".zip, .tar.gz"

dataset_splits:
  - id: 1
    name: Development Split
    codename: dev_split
  - id: 2
    name: Testing Split
    codename: test_split

challenge_phase_splits:
  - challenge_phase_id: 1
    leaderboard_id: 1
    dataset_split_id: 1
    visibility: 2
    leaderboard_decimal_precision: 2
    is_leaderboard_order_descending: False
  - challenge_phase_id: 2
    leaderboard_id: 1
    dataset_split_id: 2
    visibility: 3
    leaderboard_decimal_precision: 2
    is_leaderboard_order_descending: False
